### PR TITLE
use DeviceEventEmitter

### PR DESCRIPTION
**Pull request by bartonhammond**
Tested on iOS

### CODE REVIEW

**Comment by kenwheeler** [comment]
Gotta test this on Android, but LGTM

**Comment by jimthedev** [comment]
@kenwheeler @bartonhammond any update on this?

**Comment by bartonhammond** [comment]
I'm not using it now.

**Comment by jimthedev** [comment]
@bartonhammond mind if I ask what you are using instead?

**Comment by bartonhammond** [comment]
I'm not using any orientation module at this time.

**Pull request merged**
